### ISSUE TITLE
When object is callable

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Dispatcher#10]
When object is callable ie when `__invoke` method exists but the method not there. The callable returns true and there by returning cannot call the method.

https://github.com/auraphp/Aura.Dispatcher/blob/develop-2/src/Dispatcher.php#L116

**Comment by pmjones** [comment]
fixed by fec7c7a

**Comment by harikt** [comment]
oh auto close didn't worked . :( .

**Comment by pmjones** [comment]
needs to be `fixes #__`, not `fixes issue #__`

**Comment by harikt** [comment]
aah. Thanks.

_Hari K T_

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/auraphp ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt
