### ISSUE TITLE
Stray DocBlock in DispatcherInterface

### ISSUE THREAD

**Issue by AkenRoberts** [auraphp/Aura.Dispatcher#14]
[Looks like a duplicate DocBlock went wandering.](https://github.com/auraphp/Aura.Dispatcher/blob/develop-2/src/DispatcherInterface.php#L54-L62)

**Comment by pmjones** [comment]
Ha! It's nice to see someone actually reading code. Send a PR if you like, and I'll merge it so you get credit automatically.

**Comment by AkenRoberts** [comment]
PR'ed!

**Comment by harikt** [comment]
Hm, I was looking and didn't noticed what was wrong for the link points to the fixed one. Spend sometime to recognize it . For history https://github.com/auraphp/Aura.Dispatcher/blob/aed5a94b89ee4ca84358c107926c487ef295c2b1/src/DispatcherInterface.php#L54-L72

**Comment by AkenRoberts** [comment]
Good catch. I forgot that the link would be useless once the code was fixed.

**Comment by harikt** [comment]
updated the contributors list http://auraphp.com/contributors/ . So you have a place there.

Thanks.

**Comment by AkenRoberts** [comment]
Very nice of you! Cheers.
