### ISSUE TITLE
weird inconsistent headings

### ISSUE THREAD

**Issue by cordoval** [auraphp/Aura.Dispatcher#18]
most of the classes have, but some under config/Common.php don't

what is the reasoning? thanks

```
/**
 *
 * This file is part of Aura for PHP.
 *
 * @package Aura.Project_Kernel
 *
 * @license http://opensource.org/licenses/bsd-license.php BSD
 *
 */
```

**Comment by harikt** [comment]
If it is missing, it is for we forgot to add.

**Comment by cordoval** [comment]
in that case I propose to use gush meta-header command to solve this issue, it is less error prone and more automated, it will require just a .gush.yml file at the root of the project and will always take care of this. We can do this with all packages once you see it working for yourself. ping @pmjones @harikt

**Comment by pmjones** [comment]
If there's a missing file- or class-level DocBlock in a particular package, yes, it needs to be added. Place an issue against the respective repository and we can address it.
