### ISSUE TITLE
Magic Methods

### ISSUE THREAD

**Issue by jk3us** [auraphp/Aura.Dispatcher#20]
I've having a look at Aura.Dispatcher for calling simple/generic controllers.  I'm currently playing with it from klein.

I'm a little confused about the use of __invoke in the documentation.  You suggest calling `$dispatcher->__invoke($params)`, but the whole point of the magic method `__invoke()` is to allow you to call a class instance as if it were a function.... and `$dispatcher($params)` works exactly the same, and looks a lot better.

Is there are reason that you choose to call `__invoke()` directly instead of letting the PHP [magic](http://php.net/manual/en/language.oop5.magic.php) take affect?

**Comment by pmjones** [comment]
> Is there are reason that you choose to call __invoke() directly instead of letting the PHP magic take affect?

No reason other than explicitness in the docs; that is, I wanted it to be obvious that __invoke() is what is actually getting called. Do you feel it is jarring or otherwise suboptimal?

**Comment by jk3us** [comment]
I guess my feeling is that there are very few reasons to explicitly call php's magic methods.  If you intend for them to be explicitly called, then you might want to choose another method name and not use the magic one at all.  In this case, since `Dispatcher::__invoke()` does little other than call `Dispatcher::dispatch()`, maybe it would be better written so that users would just call `dispatch()` themselves instead of `__invoke()` or just `$dispatcher()`.

Not something I feel strongly about, but it did confuse me.

**Comment by pmjones** [comment]
Better? :-)

**Comment by jk3us** [comment]
Works for me :) Thanks.

**Comment by harikt** [comment]
iirc the first version of docs were like `$dispatcher()` which was a bit confusion ;-) . Now looks good Paul . 

Thank you @jk3us for reporting. 

In case you need a router + dispatcher example see https://github.com/harikt/router-dispatcher
