### ISSUE TITLE
New failing tests for private/missing methods

### ISSUE THREAD

**Issue by jk3us** [auraphp/Aura.Dispatcher#23]
From our discussion on PR #21, I've pushed a [couple of new tests](https://github.com/jk3us/Aura.Dispatcher/commit/03ca0bf4cf7d0bdafd03be9063758a3e6eef009f) to my [test_bad_methods](https://github.com/jk3us/Aura.Dispatcher/tree/test_bad_methods) branch. One tries to use a method that doesn't exist and one tries to call a private method.  The current dispatch function currently just returns the object that is passed in.  I didn't submit a pull request, because I'm not sure if my assumptions were right in this case.

The `invokeMethod` method never gets called, because neither of those will be reported as callable by `is_callable()` (as of [php 5.0.5](http://us3.php.net/ChangeLog-5.php#5.0.5), is_callable will not return true for private and protected methods).

I tried refactoring the dispatch function to make it work they way I was expecting, but I'm about to run out of battery on this laptop, which is my hard limit for coding on a Friday night.  However, if you simply remove the is_callable in dispatch(), the MethodNotAccessible test no longer fails.

**Comment by harikt** [comment]
Bad link to the couple of new tests :)

**Comment by harikt** [comment]
I am not in favor of Dispatcher calling a private method. Do you think we need. To me someone is making a method private means not to call it.

**Comment by jk3us** [comment]
Link fixed. And no, private methods should not work... But an exception should be thrown when you try. That's what one of the tests is for.

**Comment by harikt** [comment]
@jk3us open a PR we will see how to improve it.

Sorry to say if you love tabs, could you please make the tab to be 4 spaces ?

Thank you for considering.

**Comment by pmjones** [comment]
Closed along with #24.
